<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<CompressionEnabled>false</CompressionEnabled>
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
		<PackageReference Include="SpawnDev.BlazorJS" Version="3.3.0" />
		<PackageReference Include="Radzen.Blazor" Version="6.0.1" />
		<PackageReference Include="BlazorMonaco" Version="3.3.0" />
	</ItemGroup>
	
	<PropertyGroup>
		<!-- 
			The below RestoreAdditionalProjectSources tag is required to get 
			Microsoft.CodeAnalysis.CSharp and related packages for compiling.
		    CodeRunner uses some Microsoft packages that they do not publish 
			on the default Nuget source. The package source they use is added 
			via RestoreAdditionalProjectSources here. Package link source: 
			https://github.com/dotnet/aspnetcore/blob/main/NuGet.config
		-->
		<RestoreAdditionalProjectSources>
			https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;
		</RestoreAdditionalProjectSources>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SpawnDev.BlazorJS.CodeRunner\SpawnDev.BlazorJS.CodeRunner.csproj" />
	</ItemGroup>

</Project>
