<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>2.0.0-rc.1</Version>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<EmbedAllSources>true</EmbedAllSources>
		<DebugType>Embedded</DebugType>
		<Title>SpawnDev.BlazorJS.CodeRunner</Title>
		<Authors>LostBeard</Authors>
		<Description>Compile C# code in Blazor WebAssembly</Description>
		<PackageProjectUrl>https://github.com/LostBeard/SpawnDev.BlazorJS.CodeRunner</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon-128.png</PackageIcon>
		<RepositoryUrl>https://github.com/LostBeard/SpawnDev.BlazorJS.CodeRunner.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>Blazor;BlazorWebAssembly</PackageTags>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
	</PropertyGroup>

	
	<PropertyGroup>
		<!-- 
			The below RestoreAdditionalProjectSources tag is required to get 
			Microsoft.CodeAnalysis.CSharp and related packages for compiling.
		    CodeRunner uses some Microsoft packages that they do not publish 
			on the default Nuget source. The package source they use is added 
			via RestoreAdditionalProjectSources here. Package link source: 
			https://github.com/dotnet/aspnetcore/blob/main/NuGet.config
		-->
		<RestoreAdditionalProjectSources>
			https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;
		</RestoreAdditionalProjectSources>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AssemblyVersion>2.0.0.2</AssemblyVersion>
		<FileVersion>2.0.0.2</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
		<None Include="icon-128.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.13.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Razor" Version="6.0.36" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MetadataReferenceService.BlazorWasm\MetadataReferenceService.BlazorWasm.csproj" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

</Project>